---
Name: quaff-config
---
Injector:
  QuaffMapper:
    class: QuaffArrayMapper
QuaffModelController:
  extensions:
    - QuaffModelControllerExtension
QuaffModel:
  extensions:
    - QuaffMappableExtension